# Monaco Editor language and theme constants for Edith.

# (lang_id, display_name) — sorted alphabetically by display name.
MONACO_LANGUAGES = [
    ("abap", "ABAP"),
    ("apex", "Apex"),
    ("azcli", "Azure CLI"),
    ("bat", "Batch"),
    ("bicep", "Bicep"),
    ("c", "C"),
    ("cameligo", "CameLIGO"),
    ("clojure", "Clojure"),
    ("coffeescript", "CoffeeScript"),
    ("cpp", "C++"),
    ("csharp", "C#"),
    ("csp", "CSP"),
    ("css", "CSS"),
    ("cypher", "Cypher"),
    ("dart", "Dart"),
    ("dockerfile", "Dockerfile"),
    ("ecl", "ECL"),
    ("elixir", "Elixir"),
    ("flow9", "Flow9"),
    ("freemarker2", "FreeMarker2"),
    ("fsharp", "F#"),
    ("go", "Go"),
    ("graphql", "GraphQL"),
    ("handlebars", "Handlebars"),
    ("hcl", "HCL"),
    ("html", "HTML"),
    ("ini", "INI"),
    ("java", "Java"),
    ("javascript", "JavaScript"),
    ("json", "JSON"),
    ("julia", "Julia"),
    ("kotlin", "Kotlin"),
    ("less", "Less"),
    ("lexon", "Lexon"),
    ("liquid", "Liquid"),
    ("lua", "Lua"),
    ("m3", "Modula-3"),
    ("markdown", "Markdown"),
    ("mdx", "MDX"),
    ("mips", "MIPS"),
    ("msdax", "MSDAX"),
    ("mysql", "MySQL"),
    ("objective-c", "Objective-C"),
    ("pascal", "Pascal"),
    ("pascaligo", "PascaLIGO"),
    ("perl", "Perl"),
    ("pgsql", "PostgreSQL"),
    ("php", "PHP"),
    ("pla", "PLA"),
    ("plaintext", "Plain Text"),
    ("postiats", "ATS/Postiats"),
    ("powerquery", "Power Query"),
    ("powershell", "PowerShell"),
    ("protobuf", "Protocol Buffers"),
    ("pug", "Pug"),
    ("python", "Python"),
    ("qsharp", "Q#"),
    ("r", "R"),
    ("razor", "Razor"),
    ("redis", "Redis"),
    ("redshift", "Redshift"),
    ("restructuredtext", "reStructuredText"),
    ("ruby", "Ruby"),
    ("rust", "Rust"),
    ("sb", "Small Basic"),
    ("scala", "Scala"),
    ("scheme", "Scheme"),
    ("scss", "SCSS"),
    ("shell", "Shell"),
    ("sol", "Solidity"),
    ("sparql", "SPARQL"),
    ("sql", "SQL"),
    ("st", "Structured Text"),
    ("swift", "Swift"),
    ("systemverilog", "SystemVerilog"),
    ("tcl", "Tcl"),
    ("twig", "Twig"),
    ("typescript", "TypeScript"),
    ("vb", "Visual Basic"),
    ("wgsl", "WGSL"),
    ("xml", "XML"),
    ("yaml", "YAML"),
]

# (theme_id, display_name)
MONACO_THEMES = [
    ("vs", "Light (VS)"),
    ("vs-dark", "Dark (VS)"),
    ("hc-black", "High Contrast Dark"),
    ("hc-light", "High Contrast Light"),
    ("monokai", "Monokai"),
    ("one-dark", "One Dark"),
    ("dracula", "Dracula"),
    ("solarized-dark", "Solarized Dark"),
    ("solarized-light", "Solarized Light"),
    ("nord", "Nord"),
    ("github-light", "GitHub Light"),
    ("github-dark", "GitHub Dark"),
]

# File extension → Monaco language ID
EXT_TO_MONACO = {
    "abap": "abap",
    "bat": "bat",
    "cmd": "bat",
    "bicep": "bicep",
    "c": "c",
    "h": "c",
    "clj": "clojure",
    "cljs": "clojure",
    "coffee": "coffeescript",
    "cpp": "cpp",
    "cc": "cpp",
    "cxx": "cpp",
    "hpp": "cpp",
    "hh": "cpp",
    "hxx": "cpp",
    "cs": "csharp",
    "css": "css",
    "dart": "dart",
    "dockerfile": "dockerfile",
    "ex": "elixir",
    "exs": "elixir",
    "fs": "fsharp",
    "fsi": "fsharp",
    "fsx": "fsharp",
    "go": "go",
    "graphql": "graphql",
    "gql": "graphql",
    "hbs": "handlebars",
    "handlebars": "handlebars",
    "tf": "hcl",
    "tfvars": "hcl",
    "hcl": "hcl",
    "htm": "html",
    "html": "html",
    "xhtml": "html",
    "ini": "ini",
    "cfg": "ini",
    "conf": "ini",
    "properties": "ini",
    "java": "java",
    "js": "javascript",
    "mjs": "javascript",
    "cjs": "javascript",
    "jsx": "javascript",
    "json": "json",
    "jsonc": "json",
    "jl": "julia",
    "kt": "kotlin",
    "kts": "kotlin",
    "less": "less",
    "liquid": "liquid",
    "lua": "lua",
    "md": "markdown",
    "mkd": "markdown",
    "markdown": "markdown",
    "mdx": "mdx",
    "m": "objective-c",
    "mm": "objective-c",
    "pas": "pascal",
    "pp": "pascal",
    "pl": "perl",
    "pm": "perl",
    "php": "php",
    "phtml": "php",
    "txt": "plaintext",
    "text": "plaintext",
    "log": "plaintext",
    "ps1": "powershell",
    "psm1": "powershell",
    "psd1": "powershell",
    "proto": "protobuf",
    "pug": "pug",
    "jade": "pug",
    "py": "python",
    "pyw": "python",
    "pyi": "python",
    "r": "r",
    "R": "r",
    "cshtml": "razor",
    "rst": "restructuredtext",
    "rb": "ruby",
    "erb": "ruby",
    "gemspec": "ruby",
    "rs": "rust",
    "scala": "scala",
    "sc": "scala",
    "scm": "scheme",
    "ss": "scheme",
    "scss": "scss",
    "sh": "shell",
    "bash": "shell",
    "zsh": "shell",
    "fish": "shell",
    "sol": "sol",
    "sql": "sql",
    "swift": "swift",
    "sv": "systemverilog",
    "svh": "systemverilog",
    "tcl": "tcl",
    "twig": "twig",
    "ts": "typescript",
    "tsx": "typescript",
    "mts": "typescript",
    "cts": "typescript",
    "vb": "vb",
    "bas": "vb",
    "wgsl": "wgsl",
    "xml": "xml",
    "xsl": "xml",
    "xslt": "xml",
    "svg": "xml",
    "plist": "xml",
    "yml": "yaml",
    "yaml": "yaml",
}

_LANG_MAP = {lid: name for lid, name in MONACO_LANGUAGES}
_THEME_MAP = {tid: name for tid, name in MONACO_THEMES}


def get_language_name(lang_id: str) -> str:
    """Return display name for a Monaco language ID, or the ID itself."""
    return _LANG_MAP.get(lang_id, lang_id)


def get_theme_name(theme_id: str) -> str:
    """Return display name for a Monaco theme ID, or the ID itself."""
    return _THEME_MAP.get(theme_id, theme_id)
